### ISSUE TITLE
Do id values on commit interface need to be incremental?

### ISSUE THREAD

**Issue by Silabs-ArjanB** [openhwgroup/core-v-xif#14]
The spec currently states "The id values of subsequent commit transactions will increment (and wrap around)".

I added that myself, but there is no strong reason for this requirement other than that it will look logical. Once we have a bit more implementation feedback we need to decide if we keep or relax this requirement.

**Comment by GuillaumeChauvon** [comment]
To give input on the CVA6 implementation, the id of the instruction is linked to its scoreboard id (which increment and wrap around). So if non-offloaded instructions are placed between offloaded instructions, the id will increment but not necessary by 1.

**Comment by davideschiavone** [comment]
Hi @Silabs-ArjanB , if there are no reasons to keep it incremental, I strongly suggest removing it.
Also because in a multicore platform, cores may use as ID the tuple "core_hard_id, instruction_id", so the coprocessor may receive for example 0x00 (core0, instruction0), then 0x10 (core1, instruction0), then 0x01, then 0x11, 0x02, 0x12, etc...
