### ISSUE TITLE
Adding an User signal to CPU to COPROC interfaces

### ISSUE THREAD

**Issue by davideschiavone** [openhwgroup/core-v-xif#19]
Shall we add a USER interface in the ISSUE interface channel (x_issue_req_t) ?

Maybe also in the memory channel (x_mem_req_t).

Can be tight to 0 if no USER signal is specified. 

Generally, it can be extended to every interface (compressed, etc) but it may look ugly to have such USER signals everywhere - However, I think it may be useful for future extensions

@Silabs-ArjanB @vogelpi @moimfeld

**Comment by vogelpi** [comment]
Hi @davideschiavone ,
we have been discussing around this topic in a previous meeting. IIRC, we agreed on the following two things:
1. We didn't want to add USER signals at this moment as we want to encourage people to harmonize their designs and improve the specification at this still early point. If we add USER signals now, there is less incentive to agree on how things should be done which may result in everybody moving crucial stuff into the USER signals and having their own way of doing things. This severely limits interoperability and actually weakens the spec.
2. If we add USER signals in the future, we will add them to every channel. Otherwise people will do ugly hacks and overload the USER signal of one channel to control things in another channel. As you noted, if the signals aren't used, they are just 0.

**Comment by davideschiavone** [comment]
thanks @vogelpi +1 from my side 
Let's add them in the future to every channel after the spec is solid and retified
