### ISSUE TITLE
[Review Comment]: Feedback on XIF spec v1.0.0-rc.1

### ISSUE THREAD

**Issue by Silabs-ArjanB** [openhwgroup/core-v-xif#198]
### Comment

Please find my feedback attached.

[OpenHW_Group_Specification_Core-V_eXtension_interface_.CV-X-IF._v1.0.0-rc.1.pdf](https://github.com/openhwgroup/core-v-xif/files/14613982/OpenHW_Group_Specification_Core-V_eXtension_interface_.CV-X-IF._v1.0.0-rc.1.pdf)

### Proposed Resolution

Fix typos, resolve other issues

**Comment by christian-herber-nxp** [comment]
Hi Arjan, thanks for the detailed review. In order to make the resolutions tracible, I will have to ask you to file an issue for each item. For practical reasons, I will fix all the typos/textual corrections. For content questions, we need an actual issue, also to enable discussion with the other contributors.
